services:
  
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/usr/share/grafana/conf/provisioning
    environment:
      # Auth 
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      
      #Admin 
      - GF_SERVER_ROOT_URL=https://demo.rousseltm.fr/
      - GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasource,grafana-clock-panel
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    #command: 
    #  - grafana cli plugins install grafana-piechart-panel
    networks:
      - common-observability
    labels:
      - "org.label-schema.group=observability"    
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`demo.rousseltm.fr`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=resolversmart"   

volumes:
  grafana_data: {}

networks:
  common-observability:
    external: true