{
 "title": "projet 4",
 "tags": [ "projet 4" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "{\"find\": \"terms\", \"field\": \"host.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "response.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT response:[200 TO 3*] AND host:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Répartition des codes HTTP",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "host: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Répartition des codes HTTP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "host: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Répartition géographique des visteurs",
   "type": "geomap",
   "description": "Représentation geographique des utilisateurs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "response:503 AND machine.os:win* AND host:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Erreurs serveurs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "response:[500 TO *] AND host:$host",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}