apiVersion: 1
datasources:
  - name: datasource1
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
  
  - name: datasource2
    type: yesoreyeram-infinity-datasource
    uid: infinity

  - name: datasource3
    type: Elasticsearch
    uid: elasticsearch
    url: https://rousseltm-4707102737.us-east-1.bonsaisearch.net:443
    #basicAuth: true
    #basicAuthUser: k78ykquf60
    #withCredentials: ttjo6ry5mf