apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
  
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    uid: infinity