apiVersion: 1
datasources:
  - name: datasource1
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
  
  - name: datasource2
    type: yesoreyeram-infinity-datasource
    uid: infinity

  - name: datasource3
    type: elasticsearch
    uid: elasticsearch
    url: https://rousseltm-4707102737.us-east-1.bonsaisearch.net:443
    basicAuth: true
    basicAuthUser: k78ykquf60
    secureJsonData:
      basicAuthPassword: ttjo6ry5mf
    jsonData:
      includeFrozen": false
      logLevelField: ""
      logMessageField: ""
      maxConcurrentShardRequests: 5
      oauthPassThru: false
      pdcInjected: false
      sigV4Auth: false
      timeField: "@timestamp"